{% set name = "pyre" %}
{% set version = "1.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/pyre/pyre/archive/v{{ version }}.tar.gz
    sha256: 627c76c108696dad75357beb9fad4adc9509874511f00871866803c4317c5292
    patches:
        # Fallback clock stub for pre-10.12 SDK
        - macos-clock.patch
        # Promise minor version compatibility
        - version-compat.patch

build:
  number: 0
  skip: true  # [win or py2k or python_impl == 'pypy']

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - pybind11
    - python
    - zip
  run:
    - python

test:
  requires:
    - cmake
  commands:
    # Disable TCP test on Docker
    # Reenable locale_codec after resolving https://github.com/pyre/pyre/issues/65
    - ctest --output-on-failure -E '(pyre.pkg.ipc.tcp.py|python.locale_codec.py|pyre.pkg.codecs.yaml_|pyre.lib.timers.process_timer|pyre.pkg.timers)'
  imports:
    - pyre
    - journal

about:
  home: http://pyre.orthologue.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python framework for scientific applications

  description: |
    An open source application framework for building
    scalable, user-friendly scientific applications.

  dev_url: https://github.com/pyre/pyre
  doc_url: http://pyre.orthologue.com/docs

extra:
  recipe-maintainers:
    - aivazis
    - rtburns-jpl
